kind = "web"
previewPath = "/"
title = "W3AppDevelopers"
version = "1.0.0"
id = "artifacts/w3app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20282

[services.development]
run = "pnpm --filter @workspace/w3app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/w3app", "run", "build" ]
publicDir = "artifacts/w3app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20282"
BASE_PATH = "/"
